# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rpc_api
from rpc_api.api.geo_api import GeoApi  # noqa: E501
from rpc_api.rest import ApiException


class TestGeoApi(unittest.TestCase):
    """GeoApi unit test stubs"""

    def setUp(self):
        self.api = GeoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geo_point_by_address_get(self):
        """Test case for geo_point_by_address_get

        Geocoding à partir d'une adresse litérale  # noqa: E501
        """
        pass

    def test_geo_point_by_insee_get(self):
        """Test case for geo_point_by_insee_get

        Geocoding à partir d'un code insee  # noqa: E501
        """
        pass

    def test_geo_route_get(self):
        """Test case for geo_route_get

        Calcul théorique de la distance et de la durée  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
