# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rpc_api
from rpc_api.models.uuid_attachment_body import UuidAttachmentBody  # noqa: E501
from rpc_api.rest import ApiException


class TestUuidAttachmentBody(unittest.TestCase):
    """UuidAttachmentBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUuidAttachmentBody(self):
        """Test UuidAttachmentBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rpc_api.models.uuid_attachment_body.UuidAttachmentBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
