# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rpc_api
from rpc_api.api.attestation_api import AttestationApi  # noqa: E501
from rpc_api.rest import ApiException


class TestAttestationApi(unittest.TestCase):
    """AttestationApi unit test stubs"""

    def setUp(self):
        self.api = AttestationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_certificate_create(self):
        """Test case for certificate_create

        Créer un certificat  # noqa: E501
        """
        pass

    def test_certificate_download(self):
        """Test case for certificate_download

        Télécharger une attestation  # noqa: E501
        """
        pass

    def test_certificate_verify(self):
        """Test case for certificate_verify

        Vérifier un certificat  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
