# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rpc_api
from rpc_api.api.trajet_api import TrajetApi  # noqa: E501
from rpc_api.rest import ApiException


class TestTrajetApi(unittest.TestCase):
    """TrajetApi unit test stubs"""

    def setUp(self):
        self.api = TrajetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_acquisition_cancel(self):
        """Test case for acquisition_cancel

        Invalider un trajet envoyé  # noqa: E501
        """
        pass

    def test_acquisition_create(self):
        """Test case for acquisition_create

        Envoyer un trajet  # noqa: E501
        """
        pass

    def test_acquisition_status(self):
        """Test case for acquisition_status

        Vérifier le statut d'un trajet envoyé  # noqa: E501
        """
        pass

    def test_acquisition_update(self):
        """Test case for acquisition_update

        Mettre à jour un trajet  # noqa: E501
        """
        pass

    def test_journeys_get(self):
        """Test case for journeys_get

        Liste des trajets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
