# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rpc_api
from rpc_api.api.simuler_api import SimulerApi  # noqa: E501
from rpc_api.rest import ApiException


class TestSimulerApi(unittest.TestCase):
    """SimulerApi unit test stubs"""

    def setUp(self):
        self.api = SimulerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_policies_simulate_post(self):
        """Test case for policies_simulate_post

        Simuler une incitation sur un trajet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
