# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rpc_api
from rpc_api.models.certificatesuuidattachment_meta_identity import CertificatesuuidattachmentMetaIdentity  # noqa: E501
from rpc_api.rest import ApiException


class TestCertificatesuuidattachmentMetaIdentity(unittest.TestCase):
    """CertificatesuuidattachmentMetaIdentity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificatesuuidattachmentMetaIdentity(self):
        """Test CertificatesuuidattachmentMetaIdentity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rpc_api.models.certificatesuuidattachment_meta_identity.CertificatesuuidattachmentMetaIdentity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
