# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rpc_api
from rpc_api.models.inline_response201_meta import InlineResponse201Meta  # noqa: E501
from rpc_api.rest import ApiException


class TestInlineResponse201Meta(unittest.TestCase):
    """InlineResponse201Meta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse201Meta(self):
        """Test InlineResponse201Meta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rpc_api.models.inline_response201_meta.InlineResponse201Meta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
