# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CertificateDataTrips(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        '_datetime': 'datetime',
        'trips': 'int',
        'distance': 'Distance',
        'amount': 'float'
    }

    attribute_map = {
        'type': 'type',
        '_datetime': 'datetime',
        'trips': 'trips',
        'distance': 'distance',
        'amount': 'amount'
    }

    def __init__(self, type=None, _datetime=None, trips=None, distance=None, amount=None):  # noqa: E501
        """CertificateDataTrips - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self.__datetime = None
        self._trips = None
        self._distance = None
        self._amount = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if _datetime is not None:
            self._datetime = _datetime
        if trips is not None:
            self.trips = trips
        if distance is not None:
            self.distance = distance
        if amount is not None:
            self.amount = amount

    @property
    def type(self):
        """Gets the type of this CertificateDataTrips.  # noqa: E501


        :return: The type of this CertificateDataTrips.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CertificateDataTrips.


        :param type: The type of this CertificateDataTrips.  # noqa: E501
        :type: str
        """
        allowed_values = ["driver", "passenger"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def _datetime(self):
        """Gets the _datetime of this CertificateDataTrips.  # noqa: E501


        :return: The _datetime of this CertificateDataTrips.  # noqa: E501
        :rtype: datetime
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime):
        """Sets the _datetime of this CertificateDataTrips.


        :param _datetime: The _datetime of this CertificateDataTrips.  # noqa: E501
        :type: datetime
        """

        self.__datetime = _datetime

    @property
    def trips(self):
        """Gets the trips of this CertificateDataTrips.  # noqa: E501


        :return: The trips of this CertificateDataTrips.  # noqa: E501
        :rtype: int
        """
        return self._trips

    @trips.setter
    def trips(self, trips):
        """Sets the trips of this CertificateDataTrips.


        :param trips: The trips of this CertificateDataTrips.  # noqa: E501
        :type: int
        """

        self._trips = trips

    @property
    def distance(self):
        """Gets the distance of this CertificateDataTrips.  # noqa: E501


        :return: The distance of this CertificateDataTrips.  # noqa: E501
        :rtype: Distance
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this CertificateDataTrips.


        :param distance: The distance of this CertificateDataTrips.  # noqa: E501
        :type: Distance
        """

        self._distance = distance

    @property
    def amount(self):
        """Gets the amount of this CertificateDataTrips.  # noqa: E501

        montant en centimes d'euros  # noqa: E501

        :return: The amount of this CertificateDataTrips.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this CertificateDataTrips.

        montant en centimes d'euros  # noqa: E501

        :param amount: The amount of this CertificateDataTrips.  # noqa: E501
        :type: float
        """

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CertificateDataTrips, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CertificateDataTrips):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
