# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse201Meta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tz': 'str',
        'positions': 'list[Geopoint]',
        'driver': 'CertificateData',
        'passenger': 'CertificateData'
    }

    attribute_map = {
        'tz': 'tz',
        'positions': 'positions',
        'driver': 'driver',
        'passenger': 'passenger'
    }

    def __init__(self, tz=None, positions=None, driver=None, passenger=None):  # noqa: E501
        """InlineResponse201Meta - a model defined in Swagger"""  # noqa: E501
        self._tz = None
        self._positions = None
        self._driver = None
        self._passenger = None
        self.discriminator = None
        if tz is not None:
            self.tz = tz
        if positions is not None:
            self.positions = positions
        if driver is not None:
            self.driver = driver
        if passenger is not None:
            self.passenger = passenger

    @property
    def tz(self):
        """Gets the tz of this InlineResponse201Meta.  # noqa: E501


        :return: The tz of this InlineResponse201Meta.  # noqa: E501
        :rtype: str
        """
        return self._tz

    @tz.setter
    def tz(self, tz):
        """Sets the tz of this InlineResponse201Meta.


        :param tz: The tz of this InlineResponse201Meta.  # noqa: E501
        :type: str
        """

        self._tz = tz

    @property
    def positions(self):
        """Gets the positions of this InlineResponse201Meta.  # noqa: E501


        :return: The positions of this InlineResponse201Meta.  # noqa: E501
        :rtype: list[Geopoint]
        """
        return self._positions

    @positions.setter
    def positions(self, positions):
        """Sets the positions of this InlineResponse201Meta.


        :param positions: The positions of this InlineResponse201Meta.  # noqa: E501
        :type: list[Geopoint]
        """

        self._positions = positions

    @property
    def driver(self):
        """Gets the driver of this InlineResponse201Meta.  # noqa: E501


        :return: The driver of this InlineResponse201Meta.  # noqa: E501
        :rtype: CertificateData
        """
        return self._driver

    @driver.setter
    def driver(self, driver):
        """Sets the driver of this InlineResponse201Meta.


        :param driver: The driver of this InlineResponse201Meta.  # noqa: E501
        :type: CertificateData
        """

        self._driver = driver

    @property
    def passenger(self):
        """Gets the passenger of this InlineResponse201Meta.  # noqa: E501


        :return: The passenger of this InlineResponse201Meta.  # noqa: E501
        :rtype: CertificateData
        """
        return self._passenger

    @passenger.setter
    def passenger(self, passenger):
        """Sets the passenger of this InlineResponse201Meta.


        :param passenger: The passenger of this InlineResponse201Meta.  # noqa: E501
        :type: CertificateData
        """

        self._passenger = passenger

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse201Meta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse201Meta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
