# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse201(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'created_at': 'datetime',
        'meta': 'InlineResponse201Meta'
    }

    attribute_map = {
        'uuid': 'uuid',
        'created_at': 'created_at',
        'meta': 'meta'
    }

    def __init__(self, uuid=None, created_at=None, meta=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._created_at = None
        self._meta = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if created_at is not None:
            self.created_at = created_at
        if meta is not None:
            self.meta = meta

    @property
    def uuid(self):
        """Gets the uuid of this InlineResponse201.  # noqa: E501


        :return: The uuid of this InlineResponse201.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this InlineResponse201.


        :param uuid: The uuid of this InlineResponse201.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def created_at(self):
        """Gets the created_at of this InlineResponse201.  # noqa: E501


        :return: The created_at of this InlineResponse201.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this InlineResponse201.


        :param created_at: The created_at of this InlineResponse201.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def meta(self):
        """Gets the meta of this InlineResponse201.  # noqa: E501


        :return: The meta of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this InlineResponse201.


        :param meta: The meta of this InlineResponse201.  # noqa: E501
        :type: InlineResponse201Meta
        """

        self._meta = meta

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse201, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse201):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
