# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PaymentsInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'index': 'float',
        'amount': 'float',
        'siret': 'str',
        'type': 'str'
    }

    attribute_map = {
        'index': 'index',
        'amount': 'amount',
        'siret': 'siret',
        'type': 'type'
    }

    def __init__(self, index=None, amount=None, siret=None, type=None):  # noqa: E501
        """PaymentsInner - a model defined in Swagger"""  # noqa: E501
        self._index = None
        self._amount = None
        self._siret = None
        self._type = None
        self.discriminator = None
        self.index = index
        self.amount = amount
        self.siret = siret
        self.type = type

    @property
    def index(self):
        """Gets the index of this PaymentsInner.  # noqa: E501

        Ordre d'application  # noqa: E501

        :return: The index of this PaymentsInner.  # noqa: E501
        :rtype: float
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this PaymentsInner.

        Ordre d'application  # noqa: E501

        :param index: The index of this PaymentsInner.  # noqa: E501
        :type: float
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501

        self._index = index

    @property
    def amount(self):
        """Gets the amount of this PaymentsInner.  # noqa: E501

        Montant du paiement en centimes d'euros  # noqa: E501

        :return: The amount of this PaymentsInner.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this PaymentsInner.

        Montant du paiement en centimes d'euros  # noqa: E501

        :param amount: The amount of this PaymentsInner.  # noqa: E501
        :type: float
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def siret(self):
        """Gets the siret of this PaymentsInner.  # noqa: E501

        Numéro de SIRET du payeur  # noqa: E501

        :return: The siret of this PaymentsInner.  # noqa: E501
        :rtype: str
        """
        return self._siret

    @siret.setter
    def siret(self, siret):
        """Sets the siret of this PaymentsInner.

        Numéro de SIRET du payeur  # noqa: E501

        :param siret: The siret of this PaymentsInner.  # noqa: E501
        :type: str
        """
        if siret is None:
            raise ValueError("Invalid value for `siret`, must not be `None`")  # noqa: E501

        self._siret = siret

    @property
    def type(self):
        """Gets the type of this PaymentsInner.  # noqa: E501

        Nom du titre  # noqa: E501

        :return: The type of this PaymentsInner.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PaymentsInner.

        Nom du titre  # noqa: E501

        :param type: The type of this PaymentsInner.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentsInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentsInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
