# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: technique@covoiturage.beta.gouv.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PoliciesSimulateBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operator_class': 'OperatorClass',
        'start': 'TimeGeopoint',
        'end': 'TimeGeopoint',
        'distance': 'Distance',
        'driver': 'Driver',
        'passenger': 'Passenger'
    }

    attribute_map = {
        'operator_class': 'operator_class',
        'start': 'start',
        'end': 'end',
        'distance': 'distance',
        'driver': 'driver',
        'passenger': 'passenger'
    }

    def __init__(self, operator_class=None, start=None, end=None, distance=None, driver=None, passenger=None):  # noqa: E501
        """PoliciesSimulateBody - a model defined in Swagger"""  # noqa: E501
        self._operator_class = None
        self._start = None
        self._end = None
        self._distance = None
        self._driver = None
        self._passenger = None
        self.discriminator = None
        self.operator_class = operator_class
        self.start = start
        self.end = end
        self.distance = distance
        self.driver = driver
        self.passenger = passenger

    @property
    def operator_class(self):
        """Gets the operator_class of this PoliciesSimulateBody.  # noqa: E501


        :return: The operator_class of this PoliciesSimulateBody.  # noqa: E501
        :rtype: OperatorClass
        """
        return self._operator_class

    @operator_class.setter
    def operator_class(self, operator_class):
        """Sets the operator_class of this PoliciesSimulateBody.


        :param operator_class: The operator_class of this PoliciesSimulateBody.  # noqa: E501
        :type: OperatorClass
        """
        if operator_class is None:
            raise ValueError("Invalid value for `operator_class`, must not be `None`")  # noqa: E501

        self._operator_class = operator_class

    @property
    def start(self):
        """Gets the start of this PoliciesSimulateBody.  # noqa: E501


        :return: The start of this PoliciesSimulateBody.  # noqa: E501
        :rtype: TimeGeopoint
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this PoliciesSimulateBody.


        :param start: The start of this PoliciesSimulateBody.  # noqa: E501
        :type: TimeGeopoint
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def end(self):
        """Gets the end of this PoliciesSimulateBody.  # noqa: E501


        :return: The end of this PoliciesSimulateBody.  # noqa: E501
        :rtype: TimeGeopoint
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this PoliciesSimulateBody.


        :param end: The end of this PoliciesSimulateBody.  # noqa: E501
        :type: TimeGeopoint
        """
        if end is None:
            raise ValueError("Invalid value for `end`, must not be `None`")  # noqa: E501

        self._end = end

    @property
    def distance(self):
        """Gets the distance of this PoliciesSimulateBody.  # noqa: E501


        :return: The distance of this PoliciesSimulateBody.  # noqa: E501
        :rtype: Distance
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this PoliciesSimulateBody.


        :param distance: The distance of this PoliciesSimulateBody.  # noqa: E501
        :type: Distance
        """
        if distance is None:
            raise ValueError("Invalid value for `distance`, must not be `None`")  # noqa: E501

        self._distance = distance

    @property
    def driver(self):
        """Gets the driver of this PoliciesSimulateBody.  # noqa: E501


        :return: The driver of this PoliciesSimulateBody.  # noqa: E501
        :rtype: Driver
        """
        return self._driver

    @driver.setter
    def driver(self, driver):
        """Sets the driver of this PoliciesSimulateBody.


        :param driver: The driver of this PoliciesSimulateBody.  # noqa: E501
        :type: Driver
        """
        if driver is None:
            raise ValueError("Invalid value for `driver`, must not be `None`")  # noqa: E501

        self._driver = driver

    @property
    def passenger(self):
        """Gets the passenger of this PoliciesSimulateBody.  # noqa: E501


        :return: The passenger of this PoliciesSimulateBody.  # noqa: E501
        :rtype: Passenger
        """
        return self._passenger

    @passenger.setter
    def passenger(self, passenger):
        """Sets the passenger of this PoliciesSimulateBody.


        :param passenger: The passenger of this PoliciesSimulateBody.  # noqa: E501
        :type: Passenger
        """
        if passenger is None:
            raise ValueError("Invalid value for `passenger`, must not be `None`")  # noqa: E501

        self._passenger = passenger

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoliciesSimulateBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoliciesSimulateBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
